language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
#sudo apt-get install 

install: sudo aptitude install -y $(< requirements) && pip install -r test_requirements.txt --use-mirrors
# command to run tests
script: make ci_test
