language: python
python:
  - "2.7"
# command to install dependencies
install: LDFLAGS=-lm sudo aptitude install -y $(< requirements) && pip install -r test_requirements.txt --use-mirrors

# command to run tests
script: sudo ./install-opencv.sh && PYTHONPATH=$PYTHONPATH:.:/usr/local/lib/python2.7/site-packages/ make ci_test
