language: python
python:
  - "2.7"
# command to install dependencies
#sudo apt-get install 

#install: sudo ./install-opencv.sh && LDFLAGS=-lm sudo aptitude install -y $(< requirements) && pip install -r test_requirements.txt --use-mirrors
install: virtualenv --python=python2.7 --system-site-packages && source ~/virtualenv/frec_venv/bin/activate && LDFLAGS=-lm sudo aptitude install -y $(< requirements) && pip install -r test_requirements.txt --use-mirrors
# command to run tests
script: make ci_test
