language: python
python:
  - "2.7"
# command to install dependencies
install:
    - sudo apt-get remove -y ffmpeg x264 libx264-dev
    - sudo apt-get update -y
    - LDFLAGS=-lm sudo aptitude install -y $(< requirements)
    - INSTALLDIR=$(python -c "import os; import numpy; print(os.path.dirname(numpy.__file__))")
    - PYTHONPATH=$PYTHONPATH:.:/usr/local/lib/python2.7/site-packages/:$INSTALLDIR pip install -r test_requirements.txt --use-mirrors

# command to run tests
script:
    - sudo ./install-opencv.sh
    - PYTHONPATH=$PYTHONPATH:.:/usr/local/lib/python2.7/site-packages/ make ci_test

