language: python
python:
  - "2.7"
# command to install dependencies
install: LDFLAGS=-lm sudo aptitude install -y $(< requirements) && pip install -r test_requirements.txt --use-mirrors

# command to run tests
script: sudo ./install-opencv.sh && make ci_test
